name: Build main node
description: Build the new docker image, push it to GCR and update the running container

inputs:
  workload_identity_provider:
    required: true
    description: OIDC
    default: "projects/763564183085/locations/global/workloadIdentityPools/github-actions-terraform-pool/providers/github-actions-provider"
  service_account:
    required: true
    description: Service account principal
    default: "github-actions-terraform@archy-f06ed.iam.gserviceaccount.com"
  UQAM_FLAG:
    required: true
    description: Inputs provided to the docker image
  UQAM_PASSPHRASE:
    required: true
    description: Inputs provided to the docker image
  DISCORD_API_TOKEN_PROD:
    required: true
    description: Inputs provided to the docker image
  GOOGLE_APPLICATION_CREDENTIALS:
    required: true
    description: Inputs provided to the docker image

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: ">= 363.0.0"

    - name: Docker - Build the main node
      run: |
        docker build -t us.gcr.io/archy-f06ed/archy-prod \
        --build-arg UQAM_FLAG='${{ inputs.UQAM_FLAG }}' \
        --build-arg UQAM_PASSPHRASE='${{ inputs.UQAM_PASSPHRASE }}' \
        --build-arg DISCORD_API_TOKEN_PROD='${{ inputs.DISCORD_API_TOKEN_PROD }}' \
        --build-arg GOOGLE_APPLICATION_CREDENTIALS='${{ inputs.GOOGLE_APPLICATION_CREDENTIALS }}' \
        -f Dockerfile.prod .
      shell: bash

    - name: Docker - Login to GCR
      run: gcloud auth configure-docker us.gcr.io -q
      shell: bash

    - name: Docker - Push to GCR
      run: docker push us.gcr.io/archy-f06ed/archy-prod
      shell: bash

    - name: Update running container
      run: gcloud compute instances update-container --zone=us-central1-a e2-micro-archy 
      shell: bash
