FROM python:3.12

WORKDIR /app

# Copy source code
COPY . .

# Install requirements
RUN pip install -r requirements.txt

# Run cloud function locally
CMD functions-framework --target=$FUNCTION_TARGET
