@startuml classDiagram
!include _common.style

set namespaceSeparator none


title Archy Firestore
center footer Archy project - Firestore class diagram


folder "servers: Collection" {
    folder "serverId: SubCollection" {
        folder "channels: Collection" {
            class "channelName: Document" {
                active: bool
                channel_id: string
            }
        }

        folder "functions: Collection" {
            class "functionName: Document" {
                active: bool
                description: string
                examples: [example: string]
                count: int
            }
        }

        folder "levels: Collection" {
            class "levelNumber: Document" {
                roles: [roleId: string]
            }
        }

        folder "users: Collection" {
            class "userId: Document" {
                avatar_url: string
                exp_toward_next_level: int
                last_message_timestamp: date
                level: int
                message_count: int
                total_exp: int
                username: string
            }
        }

        folder "warnings: Collection" {
            class "id: Document" {
                admin_id: string
                admin_username: string
                comment: string
                server_id: string
                timestamp: date
                user_id: string
            }
        }
    }
}


@enduml
