name: Build main node

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build main node with composite action
        uses: ./.github/actions/build-main-node
        with:
          UQAM_FLAG: ${{ secrets.UQAM_FLAG }}
          UQAM_PASSPHRASE: ${{ secrets.UQAM_PASSPHRASE }}
          DISCORD_API_TOKEN_PROD: ${{ secrets.DISCORD_API_TOKEN_PROD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
