name: Build main node

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/763564183085/locations/global/workloadIdentityPools/github-actions-terraform-pool/providers/github-actions-provider"
          service_account: "github-actions-terraform@archy-f06ed.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      
      - name: Docker - Build the main node
        run: docker build -t us.gcr.io/archy-f06ed/archy-prod -f Dockerfile.prod .

      - name: Docker - Push to GCR
        run: docker push us.gcr.io/archy-f06ed/archy-prod
