name: golangci-lint
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          data=$(find . -type f -name "*.go" -exec jq -n --arg path {} '$path' \; | jq -n -s '{ items: inputs }')
          echo "::set-output name=matrix::{\"include\":$(echo $data)}"
  golangci:
    name: lint
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: 
        items: ${{fromJson(needs.matrix_prep.outputs.matrix.items)}}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.items }}
