name: golangci-lint
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - id: set-matrix
        run: |
          go_folder=$(find . -type f -name "*.go" -not -path "*/cmd/*.go" -exec jq -n --arg path {} '$path' \;)
          clean_paths=$( echo $go_folder | python -c "import sys;import re; tmp=sys.stdin.read(); print(re.sub('[^/]*.go\"', '\"', tmp))")
          json_data=$(echo $clean_paths | jq -n -s '{ items: inputs }')
          echo "::set-output name=matrix::$(echo $json_data)"
  golangci:
    name: lint
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    steps:
      - name: test
        run: echo ${{ matrix.items }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=./src/.golangci.yml
          working-directory: ${{ matrix.items }}
