name: golangci-lint
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          toto=$(find . -type f -name "*.go" -exec dirname "{}" \; | sort -u | python -c 'import sys; import json; paths=sys.stdin.read().splitlines(); print(json.dumps(paths)[1:-1])')
          jsonVar=$(jq -n --arg toto "$toto" '{data: [$toto]}')
          echo "::set-output name=matrix::{$(echo $jsonVar)}"
  golangci:
    name: lint
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{needs.matrix_prep.outputs.matrix.data}}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix }}
