name: golangci-lint
on:
  - push
  - pull_request
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-path:
          [
            "ban",
            "channelMessage",
            "cloudErrorLog",
            "froge",
            "go",
            "privateMessage",
            "updateUserRole",
          ]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

          working-directory: ./src/functions/${{ matrix.go-path }}
