name: Terraform plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main

jobs:
  plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Terraform working directory based on branch
        run: |
          if [ github.base_ref = 'dev' ]; then
            echo "TF_WORKING_DIR=terraform/environments/dev" >> $GITHUB_ENV
          elif [ github.base_ref = 'main' ]; then
            echo "TF_WORKING_DIR=terraform/environments/prod" >> $GITHUB_ENV
          fi

      - name: Show TF_WORKING_DIR
        run: echo "TF_WORKING_DIR is $TF_WORKING_DIR"

      - name: Terraform plan with composite action
        uses: ./.github/actions/terraform-plan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_working_directory: ${{ env.TF_WORKING_DIR }}
