name: Terraform plan prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  TF_WORKING_DIR: terraform/environments/prod

jobs:
  plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"

      - name: Terraform with composite action
        uses: ./.github/actions/terraform-plan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_working_directory: ${{ env.TF_WORKING_DIR }}
