name: Terraform apply dev

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/dev
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/763564183085/locations/global/workloadIdentityPools/github-actions-terraform-pool/providers/github-actions-provider"
          service_account: "github-actions-terraform@archy-f06ed.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform lint
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
